spring:
  application:
    name: springboot

  jpa:
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create


  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: admin

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    enabled: true
    enable-spring-el-compiler: true
    prefix: /WEB-INF/pages/
    suffix: .html

server:
  port: 80


